export const SYSFEERIE_CFG = {};

SYSFEERIE_CFG.DIFFICULTY = {
    SIMPLE: 4,
    TOUGH: 2,
    INTRICATE: 0,
    INSANE: -2,
    RIDICULOUS: -4
};

SYSFEERIE_CFG.SIGNIFICANCE= {
    SHOULD_SUCCEED: 4,
    INTERESTING_SUCCESS: 2,
    NEUTRAL: 0,
    INTERESTING_FAIL: -2,
    SHOULD_FAIL: -4
};
